version: '3'

services:

  frontend:
    image: front:tp5
    container_name: frontend
    labels:
      - "traefik.http.routers.frontkend.rule=Host(`frontend.localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  backend:
    image: back:tp5
    container_name: backend
    labels:
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=5001"

  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
    - "--api.insecure=true"
    - "--providers.docker=true"
    - "--entrypoints.web.address=:80"
    ports:
    - "80:80"
    - "8080:8080"
    - "5001:5001"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
